from enum import StrEnum


class SourceControlReason(StrEnum):
    ACCESS_DENIED = "ACCESS_DENIED"
    BINDING_CONFLICT = "BINDING_CONFLICT"
    BRANCH_BINDING_MISSING = "BRANCH_BINDING_MISSING"
    CONNECTOR_UNAVAILABLE = "CONNECTOR_UNAVAILABLE"
    EXTERNAL_MERGE_DRIFT = "EXTERNAL_MERGE_DRIFT"
    EXTERNAL_RESULT_UNKNOWN = "EXTERNAL_RESULT_UNKNOWN"
    HEAD_SHA_CHANGED = "HEAD_SHA_CHANGED"
    MERGE_ACTOR_INELIGIBLE = "MERGE_ACTOR_INELIGIBLE"
    MERGE_CONFLICT = "MERGE_CONFLICT"
    MR_CHECKS_BLOCKED = "MR_CHECKS_BLOCKED"
    MR_CLOSED = "MR_CLOSED"
    MR_CONFLICT = "MR_CONFLICT"
    NO_DELIVERY_COMMIT = "NO_DELIVERY_COMMIT"
    OWNER_INELIGIBLE = "OWNER_INELIGIBLE"
    OWNER_MISMATCH = "OWNER_MISMATCH"
    OWNER_UNASSIGNED = "OWNER_UNASSIGNED"
    PROJECT_PROFILE_UNSUPPORTED = "PROJECT_PROFILE_UNSUPPORTED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    RECONCILIATION_PENDING = "RECONCILIATION_PENDING"
    REPOSITORY_NOT_AUTHORIZED = "REPOSITORY_NOT_AUTHORIZED"
    REPOSITORY_REMOVED = "REPOSITORY_REMOVED"
    SOURCE_BRANCH_MISSING_AFTER_INTEGRATION = "SOURCE_BRANCH_MISSING_AFTER_INTEGRATION"
    TARGET_BRANCH_NOT_FOUND = "TARGET_BRANCH_NOT_FOUND"
    TARGET_BRANCH_NOT_PROTECTED = "TARGET_BRANCH_NOT_PROTECTED"


REQUIREMENT_DELIVERY_REASONS = frozenset(
    {
        SourceControlReason.OWNER_MISMATCH,
        SourceControlReason.OWNER_INELIGIBLE,
        SourceControlReason.MERGE_ACTOR_INELIGIBLE,
        SourceControlReason.REPOSITORY_NOT_AUTHORIZED,
        SourceControlReason.BRANCH_BINDING_MISSING,
        SourceControlReason.TARGET_BRANCH_NOT_FOUND,
        SourceControlReason.TARGET_BRANCH_NOT_PROTECTED,
        SourceControlReason.NO_DELIVERY_COMMIT,
        SourceControlReason.HEAD_SHA_CHANGED,
        SourceControlReason.MR_CONFLICT,
        SourceControlReason.MR_CLOSED,
        SourceControlReason.MR_CHECKS_BLOCKED,
        SourceControlReason.MERGE_CONFLICT,
        SourceControlReason.PROJECT_PROFILE_UNSUPPORTED,
        SourceControlReason.SOURCE_BRANCH_MISSING_AFTER_INTEGRATION,
        SourceControlReason.EXTERNAL_MERGE_DRIFT,
        SourceControlReason.PROVIDER_UNAVAILABLE,
        SourceControlReason.RECONCILIATION_PENDING,
    }
)

CREATE_PREFLIGHT_REASONS = frozenset(
    {
        SourceControlReason.BRANCH_BINDING_MISSING,
        SourceControlReason.HEAD_SHA_CHANGED,
        SourceControlReason.MR_CONFLICT,
        SourceControlReason.NO_DELIVERY_COMMIT,
        SourceControlReason.OWNER_INELIGIBLE,
        SourceControlReason.OWNER_MISMATCH,
        SourceControlReason.PROJECT_PROFILE_UNSUPPORTED,
        SourceControlReason.REPOSITORY_NOT_AUTHORIZED,
        SourceControlReason.TARGET_BRANCH_NOT_FOUND,
        SourceControlReason.TARGET_BRANCH_NOT_PROTECTED,
    }
)

MERGE_PREFLIGHT_REASONS = frozenset(
    {
        SourceControlReason.BRANCH_BINDING_MISSING,
        SourceControlReason.EXTERNAL_MERGE_DRIFT,
        SourceControlReason.HEAD_SHA_CHANGED,
        SourceControlReason.MERGE_ACTOR_INELIGIBLE,
        SourceControlReason.MERGE_CONFLICT,
        SourceControlReason.MR_CHECKS_BLOCKED,
        SourceControlReason.MR_CLOSED,
        SourceControlReason.MR_CONFLICT,
        SourceControlReason.OWNER_MISMATCH,
        SourceControlReason.PROJECT_PROFILE_UNSUPPORTED,
        SourceControlReason.REPOSITORY_NOT_AUTHORIZED,
        SourceControlReason.TARGET_BRANCH_NOT_FOUND,
        SourceControlReason.TARGET_BRANCH_NOT_PROTECTED,
    }
)

DELIVERY_PREFLIGHT_REASONS = CREATE_PREFLIGHT_REASONS | MERGE_PREFLIGHT_REASONS
TRANSIENT_DELIVERY_INBOX_REASONS = frozenset({SourceControlReason.PROVIDER_UNAVAILABLE})


__all__: list[str] = []
