"""Public Source Control facade; other modules must not import internals."""

from sqlalchemy import Connection

from control_plane.app.modules.source_control.application import (
    ProcessIntegrationRequestResult,
    SourceControlDependencies,
    accept_binding_request,
    binding_request_payload_hash,
    get_repository_branch_binding,
    ingest_signed_gitlab_webhook,
    process_binding_request,
    process_due_source_control_inboxes,
    process_integration_merge_request,
    process_integration_mr_request,
    process_webhook_inbox,
    reconcile_due_effects,
    reconcile_due_integration_effects,
    reconcile_due_source_control_effects,
    register_workspace_repository,
    relay_binding_requests,
    relay_due_source_control_requests,
    remove_workspace_repository,
    verify_gitlab_standard_webhook,
)
from control_plane.app.modules.source_control.application import (
    list_authorized_repositories as _list_authorized_repositories,
)
from control_plane.app.modules.source_control.application import (
    validate_authorized_repository_runtime as _validate_authorized_repository_runtime,
)
from control_plane.app.modules.source_control.domain import (
    AuthorizedRepositorySummaryDto,
    BindingRequestEnvelope,
    BindingRequestInboxDto,
    BindingRequestMessageConflict,
    EffectOperation,
    EffectState,
    GitLabWebhookEnvelope,
    InboxState,
    InvalidBranchName,
    InvalidEffectTransition,
    InvalidRepositorySecretReference,
    MergeRequestBindingDto,
    MergeRequestCreationOrigin,
    MergeRequestKind,
    MergeRequestObservationDto,
    MergeRequestState,
    ProcessBindingRequestResult,
    ReconcileDueEffectsResult,
    ReconcileDueIntegrationEffectsResult,
    RelayBindingRequestsResult,
    RepositoryAuthorizationState,
    RepositoryBranchBindingDto,
    RepositoryNotFound,
    RepositoryRemoved,
    RepositoryWorkspaceConflict,
    RequirementCallbackState,
    RequirementCallbackUnavailable,
    SourceControlBatchResult,
    SourceControlDependencyUnavailable,
    SourceControlEffectDto,
    SourceControlError,
    StaleRepositoryRevision,
    VerifiedStandardWebhook,
    WebhookIdConflict,
    WebhookInboxDto,
    WebhookInboxState,
    WebhookPayloadInvalid,
    WebhookReplayRejected,
    WebhookSignatureInvalid,
    WorkspaceRepositoryDto,
    build_task_branch_name,
    transition_effect,
)
from control_plane.app.modules.source_control.ports import SecretReferencePort


def list_authorized_repositories(
    db: Connection,
    *,
    workspace_id: str,
    dependencies: SourceControlDependencies,
) -> tuple[AuthorizedRepositorySummaryDto, ...]:
    return _list_authorized_repositories(
        dependencies.repository_factory(db),
        workspace_id=workspace_id,
    )


def validate_authorized_repository_runtime(
    db: Connection,
    *,
    dependencies: SourceControlDependencies,
    secrets: SecretReferencePort,
    connection_ref: str,
) -> None:
    _validate_authorized_repository_runtime(
        dependencies.repository_factory(db),
        secrets=secrets,
        connection_ref=connection_ref,
    )


__all__ = [
    "AuthorizedRepositorySummaryDto",
    "BindingRequestEnvelope",
    "BindingRequestInboxDto",
    "BindingRequestMessageConflict",
    "EffectState",
    "EffectOperation",
    "GitLabWebhookEnvelope",
    "InboxState",
    "InvalidBranchName",
    "InvalidEffectTransition",
    "InvalidRepositorySecretReference",
    "MergeRequestBindingDto",
    "MergeRequestCreationOrigin",
    "MergeRequestKind",
    "MergeRequestObservationDto",
    "MergeRequestState",
    "ProcessIntegrationRequestResult",
    "ProcessBindingRequestResult",
    "ReconcileDueEffectsResult",
    "ReconcileDueIntegrationEffectsResult",
    "RepositoryAuthorizationState",
    "RepositoryBranchBindingDto",
    "RepositoryNotFound",
    "RepositoryRemoved",
    "RepositoryWorkspaceConflict",
    "RequirementCallbackState",
    "RequirementCallbackUnavailable",
    "RelayBindingRequestsResult",
    "SourceControlDependencies",
    "SourceControlBatchResult",
    "SourceControlDependencyUnavailable",
    "SourceControlError",
    "StaleRepositoryRevision",
    "VerifiedStandardWebhook",
    "WebhookIdConflict",
    "WebhookInboxDto",
    "SourceControlEffectDto",
    "WebhookInboxState",
    "WebhookPayloadInvalid",
    "WebhookReplayRejected",
    "WebhookSignatureInvalid",
    "WorkspaceRepositoryDto",
    "accept_binding_request",
    "binding_request_payload_hash",
    "build_task_branch_name",
    "get_repository_branch_binding",
    "ingest_signed_gitlab_webhook",
    "list_authorized_repositories",
    "process_binding_request",
    "process_due_source_control_inboxes",
    "process_integration_merge_request",
    "process_integration_mr_request",
    "reconcile_due_integration_effects",
    "process_webhook_inbox",
    "reconcile_due_effects",
    "reconcile_due_source_control_effects",
    "register_workspace_repository",
    "relay_binding_requests",
    "relay_due_source_control_requests",
    "remove_workspace_repository",
    "transition_effect",
    "validate_authorized_repository_runtime",
    "verify_gitlab_standard_webhook",
]
